name: Publish to PyPi

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version variable
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build wheel and source tarball
        run: python setup.py sdist
      - name: Create GitHub release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.vars.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
      - name: Publish distribution to PyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
    