name: Publish to PyPi

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version variable
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Build wheel and source tarball
        run: python setup.py sdist
      - name: Publish distribution to PyPi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Build other artifacts
        run: python setup.py bdist_egg
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ steps.vars.outputs.version }}
          body_path: CHANGELOG.md
          files: dist/*
    